version: '3.9'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "nc", "-z", "db", "5432"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ["nginx", "-g", "daemon off;"]

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"