version: '3.9'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./html/:/usr/share/nginx/html/
    environment:
      - DEBUG=true
      - ENVIRONMENT=production